spring:
  application:
    name: car-maintenance-tracker
  datasource:
    driver-class-name: org.postgresql.Driver

car:
  maintenance:
    tracker:
      security:
        jwt:
          expirationMs: 3600000