spring:
  application:
    name: car-maintenance-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/cmt
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
