spring:
  application:
    name: car-maintenance-tracker
  datasource:
    driver-class-name: org.postgresql.Driver

car:
  maintenance:
    tracker:
      security:
        auth-code:
          time-to-live-sec: 300
        jwt:
          expirationMs: 3600000
      email:
        from: ${EMAIL_FROM}