spring:
  application:
    name: car-maintenance-tracker
  datasource:
    driver-class-name: org.postgresql.Driver

car:
  maintenance:
    tracker:
      async:
        core-pool-size: 2
        max-pool-size: 4
        queue-capacity: 500
        thread-name-prefix: cmt-async-
      security:
        auth-code:
          time-to-live-sec: 300
        jwt:
          expirationMs: 3600000
      email:
        from: ${EMAIL_FROM}